version: "3.8"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile 
    environment:
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/spell_checking
    env_file:
      - .env      
    ports:
      - "3000:3000"
    depends_on:
      - postgres
      - flyway 

  postgres:
    image: postgres
    restart: always
    env_file:
      - .env
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: spell_checking
    ports:
      - "5432:5432"
    expose:
      - 5432     

  flyway:
    image: flyway/flyway
    volumes:
      - ./sql:/flyway/sql
    environment:
      FLYWAY_URL: jdbc:postgresql://postgres:5432/spell_checking
      FLYWAY_USER: postgres
      FLYWAY_PASSWORD: postgres
      WAIT_HOSTS: db:5432
      WAIT_BEFORE_HOSTS: 30
      WAIT_HOSTS_TIMEOUT: 120
    env_file:
      - .env
    command: ["migrate"]
    restart: on-failure:10
    depends_on:
      - postgres

volumes:
  postgres-data:
    external: true

networks:
  test-data-network: